### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [javamanatee/robert-derby-holmes_a-yankee-in-the-trenches#1]
- [x] The standard SE image CSS is missing; see [SEMoS 7.8.5](https://standardebooks.org/manual/1.8.0/single-page#7.8.5) and following.
- [x] The photos that were turned in the original and full-page don't need to be full-page here, since they're not turned.
- [ ] I don't believe the change to Follies in 7a7508e is a printer error; Folies is the French spelling, e.g. Folies Bergère, and is what they would have used. I think that can be reverted.
- [x] We don't generally consider changes to formatting, e.g. quotes to italics, as editorial, so d5caefd and 62d364c don't need to be editorial.

**Comment by javamanatee** [comment]
Hope you enjoyed family time!

I think I fixed the issues.  For Follies, I would agree, except that in Ch. 16 he did spell it "Follies", so I changed it in ch. 5 to be consistent.  Also google search turns up a lot more "divisional follies" in the context of WWI. What do you think?

One other thing I missed, I still had frontispiece as bodymatter and just changed it to frontmatter.  Back over to you.

**Comment by vr8hub** [comment]
Yeah, I can live with that. The support for "Divisional Follies" is pretty weak, but Divisional Folies is weaker. I should have checked the rest of the book; I did for the ’ops, which I still don't think is correct, but he was consistent with it. All right, I'll hand it over to Alex!

**Comment by javamanatee** [comment]
Night 'ops is weird.  I did find a couple other WWI stories in google books
that had it that way, but can't really figure out why the apostrophe is at
the beginning.  Thanks for the review.
